# version: '3.8'

# services:
#   front:
#     image: frontend-image
#     ports:
#       - "5173:5173"
#     restart: on-failure
#     networks:
#       - docswitch-net

#   backend:
#     image: backend-image
#     ports:
#       - "3000:3000"
#     restart: on-failure
#     env_file:
#       - ./backend/.env
#     networks:
#       - docswitch-net

#   mongo:
#     image: mongo:6
#     container_name: mongo
#     volumes:
#       - mongo-data:/data/db
#     networks:
#       - docswitch-net

# networks:
#   docswitch-net:
#     driver: bridge

# volumes:
#   mongo-data:


version: '3.8'

services:
  front:
    image: gopikumar1/frontend-image
    ports:
      - "5173:5173"
    restart: on-failure
    networks:
      - pulled-ds-net

  backend:
    image: gopikumar1/backend-image
    ports:
      - "3000:3000"
    restart: on-failure
    environment:
      - MONGODB_URI=mongodb://mongo:27017/DocSwitch
      - CLOUDC_APIK=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiMzE5ODhjY2Q4MjAxMmNlNjYxNjYwOGQ0ODE4ZjlmNDllNWYzZmM2MjAzZTQ5OTg2NTQwMWZmYmZiOGVkZjc4NThiY2JmMDM5NjhlNDdhODgiLCJpYXQiOjE3MzgyOTU4NTAuNDI2ODAxLCJuYmYiOjE3MzgyOTU4NTAuNDI2ODAyLCJleHAiOjQ4OTM5Njk0NTAuNDIyMTExLCJzdWIiOiI3MDAzNTI1MyIsInNjb3BlcyI6WyJ1c2VyLnJlYWQiLCJ1c2VyLndyaXRlIiwidGFzay5yZWFkIiwidGFzay53cml0ZSIsIndlYmhvb2sucmVhZCIsIndlYmhvb2sud3JpdGUiLCJwcmVzZXQucmVhZCIsInByZXNldC53cml0ZSJdfQ.PMK74YTIQLWzqe3f4aBvR6qBUYmoaregsxw6dT9jOFTqHOIRsIfBnxf6FEuuEZoe5sZg-0PvILv6gIvz7DF74BkwJ3UYiOcLeA9lOXYuqGL8y894zty75zQLiqJ9zQEKXb0ZMDGsD2tUreDLYX547sQBBQ_GYdxvosKy4o_Qo90HwSZiRytp4dnUruLawXcVEiIixCKBLi3InzjoUw0cca4-TQS1jisOVVIWvS9xQ0AzXaUxDJk3YfRer35Z0-WFNRSoltxw4AO5v30wiklx5QuFY0oMMeraKdHETJZlZjfeGspeT6ukhWJZXC__Yg56qdvtKTh5pwezYMmnTVcaThH7z6Q3bl62uaoFIdA0xS5PFj4ojQLzS2ufQHpN0osdkCL-KWHvLcciR8K2jumUGyLBkYAs9l9eraUwekXPmmrwo7EkcqmH79kyyX0XKUX9X6TB39BMXk4djjapuMQdarfgvtwnjf1UDOshM7jxIEeqZXiV5ylz5BPSlG8X_52X1l1Xut1U10Apk3pbeNQFcnfLexdqcxw4ahTyiima33_4vdQnT3PDN7Fk43z-pL5PuEiHA8ZUPhfYGnnZFbzzj82p5_yz8dbLS0yQT5o5eii61ePfo1-LjYjqkeNzGFV5PR3yyJDIxFPOJLzXX4dtNgnNTmxutc5KkjZivXfIurU
      - JWT_SECRET=eg5yf5hcrkd47hnczop07vbnce16ukhd
      - PORT=3000
      - CLOUDC_APIK1=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiZGQ3YmY5NjU2N2QxMGY3ZGZlYzg5MWI3MmNjOTlhZGU4NGU2ZjJhMWI1OWZmOGRkM2I5ZmZkYmE2OGUxMWQwMGJjNDY3ODc4NjdjNTllNzYiLCJpYXQiOjE3NDIzNzQwMDcuNzY2MDA1LCJuYmYiOjE3NDIzNzQwMDcuNzY2MDA3LCJleHAiOjQ4OTgwNDc2MDcuNzYwNzQ4LCJzdWIiOiI3MTM3MDU2MCIsInNjb3BlcyI6WyJ1c2VyLnJlYWQiLCJ1c2VyLndyaXRlIiwidGFzay5yZWFkIiwid2ViaG9vay5yZWFkIiwidGFzay53cml0ZSIsIndlYmhvb2sud3JpdGUiLCJwcmVzZXQucmVhZCIsInByZXNldC53cml0ZSJdfQ.YlnSY8fgdjPeEWwAPptTulWhNstmbC8cy8LIYxPhkQA9Ly6ifCUoZrpUhtNTGXrBpIWZUSMtDA6ai0FQ0nb9d4qchP_QkDOgDRmsQAtmREtUi071_BEZDpMn6kwt9YRYyDgG21JsooV99ACAwVqoF7_uZIAg6A-k54jDRlI0eUZ7pN3WbybCnpvsY1rc5NLHubf11HyWA-9P3IMH9AGFsHSJE3VFJ2sxfe7to078aAMxqGakbmdid8Fa4hhtWJfieU1vIao7v-XBwxmRoxYUsnENlzBRnmh6Z1OsczY2gLy3Qycjrf8mrhtcLqTVuamwpBNJO-tfUNS_DmKxfoQjYEE4MNK136jEqELe4raBjIVKNkTzJ13xQDTTx6-Yerbdg42kQ5rybQ-AX7fT1TXxOVFdx-5gELBBE77Wj6kP5AoGsremZ7kKuzdOKzMJjMQvy02oAKhDJ7UA912om1lV-nOt_2ByKVVfR3YtR7dAGwFZ4T9GGrwhWhIAffTDrvTmTliXgHrEyviOSqy0-pCAzvrpToXNa6cOXr_N7EtfBbdZuIREGz29Nwh9iUDiif_ULA0KppnbUViXVSpDY2OmhjIVcLDDgFms1pxZXkP1NY7Ato1sAtVbEesAEc0HZ6TMmiqqNdsnjjeRMfAcIRoTwm17QvJYkidlEFmQrQyEGOs
      - NODE_ENV=development
      - PDF_SERVICES_CLIENT_ID=c3725d70448e4937a76110e9b009f8ae
      - PDF_SERVICES_CLIENT_SECRET=p8e-0eVdWcl3vvKGQDecx3Q1eIsJrSwjSqB8
    networks:
      - pulled-ds-net

  mongo:
    image: mongo:6
    container_name: mongo
    volumes:
      - mongo-data:/data/db
    networks:
      - pulled-ds-net


networks:
  pulled-ds-net:
    external: true

volumes:
  mongo-data:


